const express = require("express")
const router = express.Router();
const AdminLogin = require("../controllers/Admin/AdminLogin.js")
const AddBus = require("../controllers/Admin/AddBus.js");
const AddRoute = require("../controllers/Admin/AddRoute.js");
const AddDriver = require("../controllers/Driver/AddDriver.js");
const AddTrip = require("../controllers/Admin/AddTrip.js");
const AddStop = require("../controllers/Admin/AddStop.js");
const AddRouteStop = require("../controllers/Admin/AddRouteStop.js");
const LiveTrips = require("../controllers/Admin/LiveTrips.js");
const GetBuses = require("../controllers/Admin/GetBuses.js");
const GetRoutes = require("../controllers/Admin/GetRoutes.js");
const GetDrivers = require("../controllers/Admin/GetDrivers.js");
const GetStops = require("../controllers/Admin/GetStops.js");
const GetStudents = require("../controllers/Admin/GetStudents.js");
const DeleteTrip = require("../controllers/Admin/DeleteTrip.js");
const AddStudent = require("../controllers/Student/AddStudent.js");
const GetMorningRoutes = require("../controllers/Admin/GetMorningRoutes.js");
const GetEveningRoutes = require("../controllers/Admin/GetEveningRoutes.js");
const CreateAlert = require("../controllers/Admin/CreateAlert.js");
const GetAlerts = require("../controllers/Admin/GetAlerts.js");
const DeleteAlert = require("../controllers/Admin/DeleteAlert.js");
const GetDashboardStats = require("../controllers/Admin/GetDashboardStats.js");
const DeleteBus = require("../controllers/Admin/DeleteBus.js");
const DeleteStudent = require("../controllers/Admin/DeleteStudent.js");
const SwapBus = require("../controllers/Admin/SwapBus.js");
const DeleteDriver = require("../controllers/Admin/DeleteDriver.js");
const ExportData = require("../controllers/Admin/ExportData.js");
const GetReports = require("../controllers/Admin/GetReports.js");

router.post("/login", AdminLogin);
router.post("/addbus", AddBus);
router.post("/addroute", AddRoute);
router.post("/adddriver", AddDriver);
router.post("/addtrip", AddTrip);
router.post("/addstop", AddStop);
router.post("/routes-stop", AddRouteStop);
router.post("/addstudent", AddStudent);
router.get("/livetrips", LiveTrips);
router.get("/buses", GetBuses);
router.get("/routes", GetRoutes);
router.get("/drivers", GetDrivers);
router.get("/stops", GetStops);
router.get("/morning-routes", GetMorningRoutes);
router.get("/evening-routes", GetEveningRoutes);
router.get("/students", GetStudents);
router.delete("/deletetrip/:id", DeleteTrip);
router.post("/alerts", CreateAlert);
router.get("/alerts", GetAlerts);
router.delete("/alerts/:id", DeleteAlert);
router.get("/dashboard-stats", GetDashboardStats);
router.delete("/buses/:id", DeleteBus);
router.delete("/students/:id", DeleteStudent);
router.post("/swap-bus", SwapBus);
router.delete("/drivers/:id", DeleteDriver);
router.get("/export/:module", ExportData);
router.get("/reports", GetReports);

module.exports = router;